// cz.config.js
/** @type {import('cz-git').CommitizenGitOptions} */
module.exports = {
  alias: { fd: "docs: fix typos" },
  messages: {
    type: "选择提交的类型 :",
    scope: "选择提交的范围(可选) :",
    customScope: "请输入自定义的提交范围 :",
    subject: "简短地描述本次提交 :\n",
    body: '更加详细地描述本次提交(可选). 使用 "|" 换行 :\n',
    breaking: '有哪些不兼容的重大变更(可选). 使用 "|" 换行 :\n',
    footerPrefixesSelect: "选择关联issue前缀(可选) :",
    customFooterPrefix: "输入自定义issue前缀 :",
    footer: "关联的issue(可选), 例如: #31, #I3244 :\n",
    confirmCommit: "是否提交或修改commit ?",
  },
  // prettier-ignore
  types: [
    { value: "feat",     name: "feat:     新增功能 | A new feature" },
    { value: "fix",      name: "fix:      修复BUG  | A bug fix" },
    { value: "docs",     name: "docs:     更新文档 | Documentation only changes" },
    { value: "style",    name: "style:    格式代码 | Changes that do not affect the meaning of the code" },
    { value: "refactor", name: "refactor: 重构代码 | A code change that neither fixes a bug nor adds a feature" },
    { value: "perf",     name: "perf:     提升性能 | A code change that improves performance" },
    { value: "test",     name: "test:     测试相关 | Adding missing tests or correcting existing tests" },
    { value: "build",    name: "build:    构建相关 | Changes that affect the build system or external dependencies" },
    { value: "ci",       name: "ci:       CI相关   | Changes to our CI configuration files and scripts" },
    { value: "revert",   name: "revert:   回退代码 | Revert to a commit" },
    { value: "chore",    name: "chore:    修改其他 | Other changes that do not modify src or test files" },
  ],
  scopes: [],
  useEmoji: false,
  emojiAlign: "center",
  themeColorCode: "",
  allowCustomScopes: true,
  allowEmptyScopes: true,
  customScopesAlign: "bottom",
  customScopesAlias: "自定义",
  emptyScopesAlias: "为空",
  upperCaseSubject: false,
  markBreakingChangeMode: false,
  allowBreakingChanges: ["feat", "fix"],
  breaklineNumber: 100,
  breaklineChar: "|",
  skipQuestions: [],
  issuePrefixes: [
    // 如果使用 gitee 作为开发管理
    { value: "link", name: "link:     链接 ISSUES 进行中" },
    { value: "closed", name: "closed:   标记 ISSUES 已完成" },
  ],
  customIssuePrefixAlign: "top",
  emptyIssuePrefixAlias: "为空",
  customIssuePrefixAlias: "自定义",
  allowCustomIssuePrefix: true,
  allowEmptyIssuePrefix: true,
  confirmColorize: true,
  maxHeaderLength: 100,
  maxSubjectLength: 300,
  minSubjectLength: 0,
  scopeOverrides: undefined,
  defaultBody: "",
  defaultIssues: "",
  defaultScope: "",
  defaultSubject: "",
};
